# Generated by Django 5.2.4 on 2025-08-01 07:27

import chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], max_length=20)),
                ('host', chatbot.models.EncryptedCharField(max_length=255)),
                ('port', chatbot.models.EncryptedCharField(max_length=10)),
                ('db_name', chatbot.models.EncryptedCharField(max_length=255)),
                ('username', chatbot.models.EncryptedCharField(max_length=255)),
                ('password', chatbot.models.EncryptedCharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
