# Generated by Django 5.2.4 on 2025-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_databaseconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='host',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='password',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='port',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='username',
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='file_path',
            field=models.CharField(default='db.sqlite3', max_length=255),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='label',
            field=models.CharField(default='Default SQLite3', max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('sqlite3', 'SQLite3')], default='sqlite3', max_length=20),
        ),
    ]
